/* tslint:disable */
/* eslint-disable */
/**
 * DeBank OpenAPI
 * Build for DeFi Developers.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Token } from '../models';
/**
 * TokenApi - axios parameter creator
 * @export
 */
export const TokenApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Bulk token fetching by address
         * @param {string} chainId ChainID
         * @param {Array&lt;string&gt;} ids List of token addresses, up to 100
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTokenListByIdsR: async (chainId: string, ids: Array<string>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'chainId' is not null or undefined
            if (chainId === null || chainId === undefined) {
                throw new RequiredError('chainId','Required parameter chainId was null or undefined when calling getTokenListByIdsR.');
            }
            // verify required parameter 'ids' is not null or undefined
            if (ids === null || ids === undefined) {
                throw new RequiredError('ids','Required parameter ids was null or undefined when calling getTokenListByIdsR.');
            }
            const localVarPath = `/v1/token/list_by_ids`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }

            if (ids) {
                localVarQueryParameter['ids'] = ids.join(COLLECTION_FORMATS.csv);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get token by address
         * @param {string} chainId ChainID
         * @param {string} id Ethereum Address or native token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTokenR: async (chainId: string, id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'chainId' is not null or undefined
            if (chainId === null || chainId === undefined) {
                throw new RequiredError('chainId','Required parameter chainId was null or undefined when calling getTokenR.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getTokenR.');
            }
            const localVarPath = `/v1/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TokenApi - functional programming interface
 * @export
 */
export const TokenApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Bulk token fetching by address
         * @param {string} chainId ChainID
         * @param {Array&lt;string&gt;} ids List of token addresses, up to 100
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTokenListByIdsR(chainId: string, ids: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Token>>> {
            const localVarAxiosArgs = await TokenApiAxiosParamCreator(configuration).getTokenListByIdsR(chainId, ids, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get token by address
         * @param {string} chainId ChainID
         * @param {string} id Ethereum Address or native token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTokenR(chainId: string, id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Token>> {
            const localVarAxiosArgs = await TokenApiAxiosParamCreator(configuration).getTokenR(chainId, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TokenApi - factory interface
 * @export
 */
export const TokenApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Bulk token fetching by address
         * @param {string} chainId ChainID
         * @param {Array&lt;string&gt;} ids List of token addresses, up to 100
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTokenListByIdsR(chainId: string, ids: Array<string>, options?: any): AxiosPromise<Array<Token>> {
            return TokenApiFp(configuration).getTokenListByIdsR(chainId, ids, options).then((request) => request(axios, basePath));
        },
        /**
         * Get token by address
         * @param {string} chainId ChainID
         * @param {string} id Ethereum Address or native token id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTokenR(chainId: string, id: string, options?: any): AxiosPromise<Token> {
            return TokenApiFp(configuration).getTokenR(chainId, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TokenApi - object-oriented interface
 * @export
 * @class TokenApi
 * @extends {BaseAPI}
 */
export class TokenApi extends BaseAPI {
    /**
     * Bulk token fetching by address
     * @param {string} chainId ChainID
     * @param {Array&lt;string&gt;} ids List of token addresses, up to 100
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public getTokenListByIdsR(chainId: string, ids: Array<string>, options?: any) {
        return TokenApiFp(this.configuration).getTokenListByIdsR(chainId, ids, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get token by address
     * @param {string} chainId ChainID
     * @param {string} id Ethereum Address or native token id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    public getTokenR(chainId: string, id: string, options?: any) {
        return TokenApiFp(this.configuration).getTokenR(chainId, id, options).then((request) => request(this.axios, this.basePath));
    }
}
